markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:title
title: JAYA0'S BLOG
url: http://jaya0.github.io
subscribe: http://jaya0.github.io/feed
exclude: [ README.md, newpost.rb ]
domain: jaya0.github.io
author: jaya0
email: brieftime@icloud.com
safe: true
excerpt_separator: "&nbsp;"
highlight: true
